language: ruby
rvm: [2.5.3]
install: bundle install && gem install jekyll html-proofer
script: bundle exec jekyll build && htmlproofer ./_site --url-ignore "/linkedin.com/"
env:
  global: [NOKOGIRI_USE_SYSTEM_LIBRARIES=true]
sudo: false
